/**
 * Import brand/software icons from Simple Icons.
 *
 * Source: https://github.com/simple-icons/simple-icons (CC0 1.0)
 *
 * Policy:
 * - Keep every unique brand icon (one SVG per slug)
 * - SVG only
 * - Do not modify icon paths or brand colors in stored assets
 *
 * Note: Simple Icons are CC0, but individual trademarks still apply.
 * Use icons only to represent the corresponding product/brand.
 *
 * Usage:
 *   npm install
 *   npm run import-brand-icons
 */

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const OUT_ROOT = join(process.cwd(), "public/icons/third-party/brands");
const MANIFEST_PATH = join(process.cwd(), "data/brandIconManifest.ts");
const SIMPLE_ICONS_ROOT = join(process.cwd(), "node_modules/simple-icons");
const ICONS_DIR = join(SIMPLE_ICONS_ROOT, "icons");
const METADATA_PATH = join(SIMPLE_ICONS_ROOT, "data/simple-icons.json");

const BRAND_SOURCE = "https://github.com/simple-icons/simple-icons";
const BRAND_LICENSE = "CC0-1.0";

interface SimpleIconMeta {
  title: string;
  slug: string;
  hex?: string;
  source?: string;
  guidelines?: string;
  aliases?: { title?: string; aka?: string[] };
}

interface BrandIconEntry {
  key: string;
  slug: string;
  label: string;
  path: string;
  hex?: string;
  sourceUrl?: string;
  guidelinesUrl?: string;
  license: string;
  package: "simple-icons";
}

function writeManifest(entries: BrandIconEntry[], packageVersion: string) {
  const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));
  const body = `// AUTO-GENERATED by scripts/import-brand-icons.ts — do not edit by hand.
export interface BrandIconEntry {
  key: string;
  slug: string;
  label: string;
  path: string;
  hex?: string;
  sourceUrl?: string;
  guidelinesUrl?: string;
  license: string;
  package: "simple-icons";
}

export const BRAND_ICON_SOURCE = ${JSON.stringify(BRAND_SOURCE)};
export const BRAND_ICON_LICENSE = ${JSON.stringify(BRAND_LICENSE)};
export const BRAND_ICON_PACKAGE = ${JSON.stringify(`simple-icons@${packageVersion}`)};
export const BRAND_ICON_CANONICAL_FORMAT = "svg";

export const brandIconManifest: BrandIconEntry[] = ${JSON.stringify(sorted, null, 2)} as BrandIconEntry[];

export function getBrandIcon(keyOrSlug: string): BrandIconEntry | undefined {
  return brandIconManifest.find((icon) => icon.key === keyOrSlug || icon.slug === keyOrSlug);
}

export function searchBrandIcons(query: string): BrandIconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return brandIconManifest.filter(
    (icon) =>
      icon.slug.includes(q) ||
      icon.label.toLowerCase().includes(q) ||
      icon.key.includes(q),
  );
}
`;
  writeFileSync(MANIFEST_PATH, body, "utf8");
}

function main() {
  if (!existsSync(ICONS_DIR) || !existsSync(METADATA_PATH)) {
    console.error("simple-icons package not found. Run: npm install");
    process.exit(1);
  }

  const packageJson = JSON.parse(
    readFileSync(join(SIMPLE_ICONS_ROOT, "package.json"), "utf8"),
  ) as { version: string };

  const metadata = JSON.parse(readFileSync(METADATA_PATH, "utf8")) as SimpleIconMeta[];
  const metaBySlug = new Map(metadata.map((item) => [item.slug, item]));

  rmSync(OUT_ROOT, { recursive: true, force: true });
  mkdirSync(OUT_ROOT, { recursive: true });

  const entries: BrandIconEntry[] = [];
  const svgFiles = readdirSync(ICONS_DIR).filter((file) => file.toLowerCase().endsWith(".svg"));

  for (const file of svgFiles) {
    const slug = file.replace(/\.svg$/i, "");
    const meta = metaBySlug.get(slug);
    const relPath = `${slug}.svg`;
    const outPath = join(OUT_ROOT, relPath);
    cpSync(join(ICONS_DIR, file), outPath);

    entries.push({
      key: `brand-${slug}`,
      slug,
      label: meta?.title ?? slug,
      path: `/icons/third-party/brands/${relPath}`,
      hex: meta?.hex,
      sourceUrl: meta?.source,
      guidelinesUrl: meta?.guidelines,
      license: BRAND_LICENSE,
      package: "simple-icons",
    });
  }

  writeManifest(entries, packageJson.version);

  console.log(`Imported ${entries.length} brand icons from simple-icons@${packageJson.version}`);
  console.log(`Output: ${OUT_ROOT}`);
  console.log(`Manifest: ${MANIFEST_PATH}`);
}

main();
